import re

def detect_language(query):
    """
    Определяет язык программирования из запроса.
    Возвращает (extension, language_name)
    """
    q_lower = query.lower()
    q_clean = re.sub(r'[^\w\s]', ' ', q_lower)
    words = set(q_clean.split())

    lang_map = {
        "python": (".py", "Python"),
        "пайтон": (".py", "Python"),
        "питон": (".py", "Python"),
        "javascript": (".js", "JavaScript"),
        "js": (".js", "JavaScript"),
        "джс": (".js", "JavaScript"),
        "node": (".js", "JavaScript"),
        "nodejs": (".js", "JavaScript"),
        "typescript": (".ts", "TypeScript"),
        "ts": (".ts", "TypeScript"),
        "тайпскрипт": (".ts", "TypeScript"),
        "тс": (".ts", "TypeScript"),
        "html": (".html", "HTML"),
        "хтмл": (".html", "HTML"),
        "css": (".css", "CSS"),
        "цсс": (".css", "CSS"),
        "scss": (".scss", "SCSS"),
        "sass": (".sass", "Sass"),
        "less": (".less", "Less"),
        "rust": (".rs", "Rust"),
        "раст": (".rs", "Rust"),
        "golang": (".go", "Go"),
        "го": (".go", "Go"),
        "c++": (".cpp", "C++"),
        "cpp": (".cpp", "C++"),
        "cplusplus": (".cpp", "C++"),
        "си++": (".cpp", "C++"),
        "c": (".c", "C"),
        "си": (".c", "C"),
        "c#": (".cs", "C#"),
        "csharp": (".cs", "C#"),
        "си шарп": (".cs", "C#"),
        "java": (".java", "Java"),
        "джава": (".java", "Java"),
        "kotlin": (".kt", "Kotlin"),
        "swift": (".swift", "Swift"),
        "php": (".php", "PHP"),
        "ruby": (".rb", "Ruby"),
        "руби": (".rb", "Ruby"),
        "bash": (".sh", "Bash"),
        "shell": (".sh", "Shell"),
        "шелл": (".sh", "Shell"),
        "bashscript": (".sh", "Bash"),
        "powershell": (".ps1", "PowerShell"),
        "ps": (".ps1", "PowerShell"),
        "sql": (".sql", "SQL"),
        "json": (".json", "JSON"),
        "yaml": (".yaml", "YAML"),
        "yml": (".yaml", "YAML"),
        "xml": (".xml", "XML"),
        "markdown": (".md", "Markdown"),
        "md": (".md", "Markdown"),
        "dockerfile": (".dockerfile", "Dockerfile"),
        "docker": (".dockerfile", "Dockerfile"),
        "lua": (".lua", "Lua"),
        "perl": (".pl", "Perl"),
        "r": (".r", "R"),
        "matlab": (".m", "MATLAB"),
        "scala": (".scala", "Scala"),
        "dart": (".dart", "Dart"),
        "flutter": (".dart", "Flutter/Dart"),
        "react": (".jsx", "React JSX"),
        "jsx": (".jsx", "JSX"),
        "tsx": (".tsx", "TSX"),
        "vue": (".vue", "Vue"),
        "angular": (".ts", "Angular/TypeScript"),
        "svelte": (".svelte", "Svelte"),
        "assembly": (".asm", "Assembly"),
        "asm": (".asm", "Assembly"),
        "haskell": (".hs", "Haskell"),
        "erlang": (".erl", "Erlang"),
        "elixir": (".ex", "Elixir"),
        "clojure": (".clj", "Clojure"),
        "lisp": (".lisp", "Lisp"),
        "fortran": (".f90", "Fortran"),
        "cobol": (".cob", "COBOL"),
        "pascal": (".pas", "Pascal"),
        "delphi": (".pas", "Delphi"),
        "ada": (".adb", "Ada"),
        "prolog": (".pl", "Prolog"),
        "smalltalk": (".st", "Smalltalk"),
        "objective-c": (".m", "Objective-C"),
        "objc": (".m", "Objective-C"),
        "groovy": (".groovy", "Groovy"),
        "julia": (".jl", "Julia"),
        "f#": (".fs", "F#"),
        "fsharp": (".fs", "F#"),
        "vb": (".vb", "VB.NET"),
        "vbnet": (".vb", "VB.NET"),
        "visual basic": (".vb", "VB.NET"),
        "actionscript": (".as", "ActionScript"),
        "coldfusion": (".cfm", "ColdFusion"),
        "tcl": (".tcl", "Tcl"),
        "scheme": (".scm", "Scheme"),
        "ocaml": (".ml", "OCaml"),
        "reason": (".re", "ReasonML"),
        "purescript": (".purs", "PureScript"),
        "elm": (".elm", "Elm"),
        "crystal": (".cr", "Crystal"),
        "nim": (".nim", "Nim"),
        "vlang": (".v", "V"),
        "v language": (".v", "V"),
        "zig": (".zig", "Zig"),
        "carbon": (".carbon", "Carbon"),
        "solidity": (".sol", "Solidity"),
        "sol": (".sol", "Solidity"),
        "vyper": (".vy", "Vyper"),
        "move": (".move", "Move"),
        "cairo": (".cairo", "Cairo"),
        "ink": (".ink", "Ink"),
        "wasm": (".wat", "WebAssembly"),
        "webassembly": (".wat", "WebAssembly"),
        "graphql": (".graphql", "GraphQL"),
        "gql": (".graphql", "GraphQL"),
        "prisma": (".prisma", "Prisma"),
        "terraform": (".tf", "Terraform"),
        "tf": (".tf", "Terraform"),
        "ansible": (".yml", "Ansible/YAML"),
        "puppet": (".pp", "Puppet"),
        "chef": (".rb", "Chef/Ruby"),
        "saltstack": (".sls", "SaltStack"),
        "nix": (".nix", "Nix"),
        "guix": (".scm", "Guix/Scheme"),
        "homebrew": (".rb", "Homebrew/Ruby"),
        "augeas": (".aug", "Augeas"),
        "awk": (".awk", "AWK"),
        "sed": (".sed", "Sed"),
        "m4": (".m4", "M4"),
        "makefile": (".mk", "Makefile"),
        "make": (".mk", "Makefile"),
        "cmake": (".cmake", "CMake"),
        "meson": (".meson", "Meson"),
        "bazel": (".bzl", "Bazel"),
        "gradle": (".gradle", "Gradle"),
        "sbt": (".sbt", "SBT"),
        "leiningen": (".clj", "Leiningen/Clojure"),
        "boot": (".clj", "Boot/Clojure"),
        "deps": (".edn", "Deps/EDN"),
        "tools.deps": (".edn", "Tools.deps/EDN"),
    }

    for word in words:
        if word in lang_map:
            return lang_map[word]

    for phrase, (ext, name) in lang_map.items():
        if " " in phrase and phrase in q_lower:
            return (ext, name)

    lang_patterns = [
        r'на\s+(?:языке\s+)?(\w+)',
        r'в\s+(\w+)',
        r'using\s+(\w+)',
        r'in\s+(\w+)',
    ]
    for pattern in lang_patterns:
        match = re.search(pattern, q_lower)
        if match:
            lang_word = match.group(1)
            if lang_word in lang_map:
                return lang_map[lang_word]

    return (".py", "Python")